spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  spring:
    h2:
      console:
        enabled: true
        path: /h2-console
  datasource:
    url: jdbc:h2:mem:dev
    username: sa
    password: 1111
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
decorator:
  datasource:
    p6spy:
      enable-logging: true