spring:
  datasource:
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl_auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher